### PR TITLE
Replace Sub::Name with Sub::Util

### PR DESCRIPTION
**Pull request by autarch**
The latter is part of core as of 5.22, so it's one less dep for some users.

### CODE REVIEW

**Comment by karenetheridge** [comment]
The last I recall, there was some debate as to whether we wanted to make the switch; are we confident enough in Sub::Util now, or are there still outstanding issues?

@haarg

**Comment by ilmari** [comment]
It has some issues with getting the name of subs [in deleted stashes](https://rt.cpan.org/Ticket/Display.html?id=116961) and with [explicitly cleared names](https://rt.cpan.org/Ticket/Display.html?id=116962) (the latter is just example code and can be fixed locally).

For the setting side, the code is identical to Sub::Name.

**Comment by haarg** [comment]
This PR is only using it to set sub names, so the the issue with deleted stashes shouldn't matter.  We could also replace our usage of Sub::Identify with Sub::Util, which could make that issue relevant.  However, Sub::Identify appears to suffer from the same issue, so it wouldn't be a regression.

**Comment by ilmari** [comment]
Replacing just the uses of Sub::Identify works, but replacing `Class::MOP::get_code_info()` with the example code in the Sub::Util POD made the test suite trigger the above-linked bugs. Once those are fixed, we can switch.

**Comment by ribasushi** [comment]
> @ilmari: For the setting side, the code is identical to Sub::Name.

Correcting the above statement here as well, so it meets more eyes:

The [current version of `Sub::Util`](https://metacpan.org/source/PEVANS/Scalar-List-Utils-1.45/ListUtil.xs#L1387-1495) is a copy of [`Sub::Name`'s code from several years ago](https://metacpan.org/source/ETHER/Sub-Name-0.12/Name.xs#L29-129). The [current implementation](https://metacpan.org/source/ETHER/Sub-Name-0.18/Name.xs) has moved ahead considerably, and satisfies [certain more elaborate tests](https://metacpan.org/source/ETHER/Sub-Name-0.18/t/exotic_names.t).

In addition neither `Sub::Util` nor `Sub::Name` consider the warnocked issue of [`\0` in identifiers](https://rt.cpan.org/Ticket/Display.html?id=103195).

AFAIK @haarg is working on syncing `Sub::Util` with its "logical upstream". I am not aware of anyone working on `RT#103195`.

**Comment by ilmari** [comment]
> The current version of Sub::Util is a copy of Sub::Name's code from several years ago. The current implementation has moved ahead considerably, and satisfies certain more elaborate tests.

Ah, okay. I was looking at the code for the latest stable release, which until today was 0.15, so it would not have been a regression to switch until literally hours ago.

**Comment by karenetheridge** [comment]
> so it would not have been a regression to switch until literally hours ago

Sorry about that -- last night I went through the list of my releases that were still in -TRIAL and released as stable everything that had been tested successfully in the wild (which thankfully was all of them).

**Comment by autarch** [comment]
I wish I knew why this only fails with 5.22 - https://travis-ci.org/moose/Moose/jobs/159134839

I'm declaring Sub::Util as a prereq properly, I think.

**Comment by karenetheridge** [comment]
Take a look at this from the build log:

```
Installing (without testing) List::Util~1.45 ... Done.
Installing (without testing) Sub::Util~1.40 ... Done.
```

This probably means the XS bits are broken, so Sub::Util is failing to load.  But I don't know why the travis config is installing Sub::Util 1.40, when it should already be present via 1.45. I see no issues in the PAUSE index.

**Comment by karenetheridge** [comment]
see also https://rt.cpan.org/Ticket/Display.html?id=122127 -- when we switch Moose over, we should also switch everything else in the Moose ecosystem at the same time.

**Comment by autarch** [comment]
Looks like this is passing now.

**Comment by karenetheridge** [comment]
I could put this out as a -TRIAL perhaps? If I do one this week we have until the end of January to decide whether to let it go stable. Is that long enough?

**Comment by autarch** [comment]
A trial seems like a good idea. Hopefully this change is relatively low risk, since Sub::Util is _supposed_ to do the same things as Sub::Name with a slightly different API.

**Comment by karenetheridge** [comment]
rebased to master for one more travis run..

**Comment by karenetheridge** [comment]
The build is failing due to https://rt.cpan.org/Ticket/Display.html?id=123953. Hopefully a fix will arrive soon.

**Comment by haarg** [comment]
This branch is passing now.

**Comment by karenetheridge** [comment]
I'll release this as trial after merging and releasing non-contentious stuff in a stable version unless everyone is really confident this will work just fine.  What is a reasonable minimum version of Sub::Util to require?

**Comment by karenetheridge** [comment]
At long last this is being merged (rebased, minor conflicts resolved in Changes and dist.ini) and will be released imminently as Moose-2.2100-TRIAL.

**Comment by karenetheridge** [comment]
merged to master.

**Pull request closed without merging**
