### PR TITLE
Exception doc generator refactoring

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by karenetheridge** [comment]
hey, I finally got around to looking at this.

- the tidy commit is redundant, since you then immediately go on to remove all that code anyway -- so you might as well squash that into the next commit.
- the diff of the generated build vs. master is quite significant, and reveals some issues:
        - removal of `# PODNAME` and replacement with a `package` declaration will not work with other podweaving code (results in all the woven headers and footers (NAME, encoding, AUTHORS etc being lost)
        - there many pod errors, e.g. missing newlines before =head2 tags.

I like the change of focus from attributes to methods - since the exception classes are all read-only and pre-populated when handed to the user, documenting that something isa Str, readonly and required isn't as helpful as documenting that there is an accessor method available to get that data.

**Comment by autarch** [comment]
I fixed the `PODNAME` and newline issues.

**Comment by karenetheridge** [comment]
The doc generator now replaces the original file content with the generated content, rather than inserting into the placeholder `=comment`. This was a very important detail, because you're generating the content after most of the build has completed, and therefore you're overwriting the pod elements that PodWeaver added.

This is easily seen by doing a `dzil build` and diffing it against a build from master.

**Comment by karenetheridge** [comment]
I'm merging this, with *very minor* corrections to the authordeps (it looks like you were only looking at author/doc-generator and forgot inc/GenerateDocs.pm, whose prereqs haven't changed).

I've done a diff of the full build before and after these changes, and the only file that changed at all was the exception manifest - cool! And all the changes to the manifest are great, with the common elements pulled out to the top of the document.

thanks!

**Pull request closed without merging**
