### PR TITLE
Test with more Perl versions on Travis and use Travis caching

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by karenetheridge** [comment]
I don't think we should merge this until the current Travis issues are sorted (which I'm in the middle of now).

**Comment by autarch** [comment]
It looks like the blead issue is fixed.

**Comment by autarch** [comment]
Ping.

**Comment by karenetheridge** [comment]
why the change to expressing versions more specifically? this would require more updates every time a maint release comes out. I think (e.g.) `5.26-thr` would work as well as `5.26.1-thr`, and automatically move to testing 5.26.2 when it is released.

**Comment by autarch** [comment]
I was under the impression that `5.26-thr` didn't work. If it does, that's obviously better.

**Pull request merged**
