### PR TITLE
converted Moose::Util::does_role to use UNIVERSAL::DOES

### PR DESCRIPTION
**Pull request by BraveNewPumpkin**
Perhaps simpler. Will allow more Interoperability with other role systems like Moo. For example using Test::Moose::does_ok may now work with a class that has a Moo role applied via Moo::Role->apply_roles_to_object().

### CODE REVIEW

**Comment by autarch** [comment]
I'm pretty sure DOES was added in a Perl newer than the oldest we still support.

**Comment by karenetheridge** [comment]
Many tests fail (as will be revealed by the travis report coming shortly).

It would be helpful to add some test cases so we can understand what scenarios aren't working for you that you'd like to work, as we can perhaps still find an implementation that works.

**Comment by Csson** [comment]
DOES was added in 5.10: https://metacpan.org/pod/distribution/perl/pod/perl5100delta.pod#UNIVERSAL::DOES

**Comment by haarg** [comment]
1. The previously noted backward compatibility issues
2. removing the try means unblessed refs will cause errors
3. UNIVERSAL's DOES provides different information than does_role.  Notably, it returns true for parent classes.
4. The issue you are trying to solve is a bug in Moo.  I've fixed it in https://github.com/moose/Moo/commit/228ac05f9311e2530e1dbe2b2b3bacfde9c09976, which I'll try to get into a release soon.

Even if the first two issues were resolved, I don't think we'd want to make this change due to the second two.

**Comment by karenetheridge** [comment]
@BraveNewPumpkin can you give some examples where `->does` returns a different answer than desired?

**Comment by BraveNewPumpkin** [comment]
I think that @haarg summarized the reasons pretty well why this is a bad pull request. Should I close it?

@karenetheridge I think the problem occurs when a Moo::Role is applied at runtime and then checked using the Moose does_role. @haarg I think is saying that it was a problem in Moo, for which he amazingly has already got a pull request.

**Comment by karenetheridge** [comment]
Closing, as this can be resolved in Moo (see https://github.com/moose/Moo/commit/228ac05f9311e2530e1dbe2b2b3bacfde9c09976)

**Pull request closed without merging**
