### PR TITLE
Add reference to Moose attributes manual in Moose::Manual::Roles

### PR DESCRIPTION
**Pull request by Relequestual**
I stumbled onto Moose::Manual::Roles, having very little knowledge of Moose and having never used it. It could be useful to add this link so that people can find out what attirbutes the required attributes section is referring to.

Sorry if this is the wrong branch to make a PR on, but I couldn't find the contributing documentation.

### CODE REVIEW

**Comment by karenetheridge** [comment]
thanks, merged, squashed, and released!

**Comment by karenetheridge** [comment]
PS. Moose::Manual::Contributing, and yes you got the right branch :)

**Comment by karenetheridge** [comment]
You inspired me to add a dzil config to copy that document to CONTRIBUTING.pod, which github will display to the user when preparing a pull request. \o/

**Comment by Relequestual** [comment]
Bravo! Thanks. The Manual namespace is new to me, but now I know if I see one page in the namespace, there's probably others!

I'm semi looking forward to learning dzil... it's got to be better than Dist::Inkt... =D

**Pull request closed without merging**
